### ISSUE TITLE
Separate help menu name from md file names

### ISSUE THREAD

**Issue by khalidhuseynov** [NFLabs/help#10]
Currently, hep menu naming is inferred from the `md` file names. However it puts some limitation on naming the menu items. For example, `ZeppelinHub Tokens` menu naming becomes impossible. Thus, it would be  better to have a separated way of assigning menu name and file name.

**Comment by khalidhuseynov** [comment]
@felizbear we talked about it the other day.

**Comment by corneadoug** [comment]
> For example, ZeppelinHub Tokens menu naming becomes impossible

Why?

**Comment by felizbear** [comment]
Check #11

**Comment by khalidhuseynov** [comment]
@corneadoug when naming file as `ZeppelinHub_Tokens.md`, the corresponding menu item was `Zeppelinhub tokens` and it couldn't resolve back to `ZeppelinHub_Tokens.md` by giving `404` error. And, generally, it's better to separate file naming from menu naming. 
@felizbear thanks!
