### ISSUE TITLE
We should add a contact link that sends them to support@zeppelinhub.com in help.zeppelinhub.com website.

### ISSUE THREAD

**Issue by sejunra** [NFLabs/help#24]
We should add a contact link that sends them to support@zeppelinhub.com in help.zeppelinhub.com website.

**Comment by corneadoug** [comment]
@sejunra Does this looks good?
![screen shot 2015-10-12 at 6 00 37 pm](https://cloud.githubusercontent.com/assets/710411/10424574/2df198c6-710b-11e5-9f1c-17fbdb9a56e3.png)

**Comment by sejunra** [comment]
Looks good. 






On Mon, Oct 12, 2015 at 2:01 AM -0700, "CORNEAU Damien" <notifications@github.com> wrote:












@sejunra Does this looks good?
